extensions:
  client:
    endpoints:
      - ws://localhost:9944
  event_bus:
  substrate_api:
    stale_timeout_seconds: 180 # rotate endpoint if no new blocks for 3 minutes
  telemetry:
    provider: none
  cache:
    default_ttl_seconds: 60
    default_size: 500
  merge_subscription:
    keep_alive_seconds: 60
  server:
    port: 9934
    listen_address: '0.0.0.0'
    max_connections: 2000
    http_methods:
      - path: /health
        method: health
      - path: /liveness
        method: chain_getBlockHash
    cors: all
  rate_limit: # NOTE: these settings will be adjusted based on the results of tests
    connection: # n RPC requests per second per connection
      burst: 5
      period_secs: 1
    ip: # n RPC requests per 10 seconds per ip
      burst: 50
      period_secs: 10
    # use X-Forwarded-For header to get real ip, if available (e.g. behind a load balancer).
    # WARNING: Use with caution, as this xff header can be forged.
    use_xff: true # default is false
  prometheus:
    port: 9616
    label: "dev"

middlewares:
  methods:
    - delay
    - response
    - inject_params
    - cache
    - upstream
  subscriptions:
    - merge_subscription
    - upstream

rpcs: substrate
